Use cabal new-build on travis (#15)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,68 +1,131 @@
-# This file has been generated by travis-meta-yaml 0.2.0.0
-# see https://github.com/phadej/travis-meta-yaml
-sudo: false
+# This Travis job script has been generated by a script via
+#
+#   make_travis_yml_2.hs '-o' '.travis.yml' '--irc-channel=irc.freenode.org#clash-lang' 'ghc-typelits-natnormalise.cabal'
+#
+# For more information, see https://github.com/hvr/multi-ghc-travis
+#
 language: c
-before_install:
-- export PATH=/opt/ghc/$GHCVER/bin:$PATH
-- if [ -n "$CABALVER" ]; then export PATH=/opt/cabal/$CABALVER/bin:$PATH; fi
-- export PATH=~/.local/bin:$PATH
-- if [ ! -e ~/.local/bin/stack ]; then mkdir -p ~/.local/bin; travis_retry curl -L
-  https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1
-  -C ~/.local/bin '*/stack'; fi
-- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
-  '?')]"
-- stack +RTS -N2 -RTS --version
-install:
-- if [ "$STACK_SOLVER" = "YES" ]; then stack config set resolver ghc-$(ghc --numeric-version); fi;
-  stack --no-terminal --skip-ghc-check list-dependencies|sort > installplan.txt;
-  cat installplan.txt; stack --no-terminal --skip-ghc-check setup; if diff -u $HOME/.stack-work-cache/installplan.txt
-  installplan.txt; then echo "cabal build-cache HIT"; rm -rf .stack-work; cp -a $HOME/.stack-work-cache
-  .stack-work; rm -f .stack-work/installplan.txt; else echo "cabal build-cache MISS";
-  rm -rf $HOME/.stack-work-cache; stack --no-terminal --skip-ghc-check build --test
-  --only-dependencies; fi; if [ ! -d $HOME/.stack-work-cache ]; then echo "snapshotting
-  package-db to build-cache"; cp -a .stack-work $HOME/.stack-work-cache; cp -a installplan.txt
-  $HOME/.stack-work-cache/installplan.txt; fi;
-script:
-- if [ "$PEDANTIC" = "YES" ]; then export STACKOPTS=--pedantic; fi
-- stack --no-terminal --skip-ghc-check build --test $STACKOPTS
-- stack --no-terminal --skip-ghc-check sdist
-matrix:
-  fast_finish: true
-  include:
-  - env: GHCVER=8.0.2 STACK_YAML=stack-lts9.yaml
-    addons:
-      apt:
-        packages:
-        - libgmp-dev
-    compiler: ! ': # ghc-8.0.2 STACK_YAML=stack-lts9.yaml'
-  - env: GHCVER=8.2.1
-    addons:
-      apt:
-        packages:
-        - libgmp-dev
-    compiler: ! ': # ghc-8.2.1'
-  - env: GHCVER=head CABALVER=head STACK_YAML=stack-head.yaml STACK_SOLVER=YES
-    addons:
-      apt:
-        sources:
-        - hvr-ghc
-        packages:
-        - ghc-head
-        - cabal-install-head
-        - libgmp-dev
-    compiler: ! ': # ghc-head'
-  allow_failures:
-  - env: GHCVER=head CABALVER=head STACK_YAML=stack-head.yaml STACK_SOLVER=YES
-cache:
-  directories:
-  - ~/.stack
-  - ~/.local
-  - ~/.stack-work-cache
-  apt: true
+sudo: false
+
+git:
+  submodules: false  # whether to recursively clone submodules
+
 notifications:
   irc:
-    skip_join: true
     channels:
-    - "irc.freenode.org#clash-lang"
+      - "irc.freenode.org#clash-lang"
+    skip_join: true
     template:
-    - "\x0313ghc-typelits-natnormalise\x0F/\x0306%{branch}\x0F \x0314%{commit}\x0F%{message} \x0302\x1F%{build_url}\x0F"
+      - "\x0313ghc-typelits-natnormalise\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
+
+cache:
+  directories:
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
+
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
+
+  - rm -fv $HOME/.cabal/packages/head.hackage
+
+matrix:
+  include:
+    - compiler: "ghc-8.0.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.0.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.2.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.2.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.4.1"
+      env: GHCHEAD=true
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.4.1], sources: [hvr-ghc]}}
+
+  allow_failures:
+    - compiler: "ghc-8.4.1"
+
+before_install:
+  - HC=${CC}
+  - HCPKG=${HC/ghc/ghc-pkg}
+  - unset CC
+  - "PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$PATH"
+
+install:
+  - cabal --version
+  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  - BENCH=${BENCH---enable-benchmarks}
+  - TEST=${TEST---enable-tests}
+  - HADDOCK=${HADDOCK-true}
+  - INSTALLED=${INSTALLED-true}
+  - GHCHEAD=${GHCHEAD-false}
+  - travis_retry cabal update -v
+  - "sed -i.bak 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config"
+  - rm -fv cabal.project.local
+  - "printf 'packages: \".\"\\n' > cabal.project"
+  # Overlay Hackage Package Index for GHC HEAD: https://github.com/hvr/head.hackage
+  - |
+    if $GHCHEAD; then
+      echo 'allow-newer: *:base, *:template-haskell' >> cabal.project
+      echo 'repository head.hackage' >> cabal.project
+      echo '   url: http://head.hackage.haskell.org/' >> cabal.project
+      echo '   secure: True' >> cabal.project
+      echo '   root-keys: 07c59cb65787dedfaef5bd5f987ceb5f7e5ebf88b904bbd4c5cbdeb2ff71b740' >> cabal.project
+      echo '              2e8555dde16ebd8df076f1a8ef13b8f14c66bad8eafefd7d9e37d0ed711821fb' >> cabal.project
+      echo '              8f79fd2389ab2967354407ec852cbe73f2e8635793ac446d09461ffb99527f6e' >> cabal.project
+      echo '   key-threshold: 3' >> cabal.project
+    fi
+  - cat cabal.project
+  - if $GHCHEAD; then cabal new-update head.hackage -v; fi
+  - if [ -f "./configure.ac" ]; then
+      (cd "."; autoreconf -i);
+    fi
+  - rm -f cabal.project.freeze
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dep -j2 all
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks --project-file="cabal.project" --dep -j2 all
+  - rm -rf "."/.ghc.environment.* "."/dist
+  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
+script:
+  # test that source-distributions can be generated
+  - (cd "." && cabal sdist)
+  - mv "."/dist/ghc-typelits-natnormalise-*.tar.gz ${DISTDIR}/
+  - cd ${DISTDIR} || false
+  - find . -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' \;
+  - "printf 'packages: ghc-typelits-natnormalise-*/*.cabal\\n' > cabal.project"
+  - "echo 'flags: +deverror' >> cabal.project"
+  # Overlay Hackage Package Index for GHC HEAD: https://github.com/hvr/head.hackage
+  - |
+    if $GHCHEAD; then
+      echo 'allow-newer: *:base, *:template-haskell' >> cabal.project
+      echo 'repository head.hackage' >> cabal.project
+      echo '   url: http://head.hackage.haskell.org/' >> cabal.project
+      echo '   secure: True' >> cabal.project
+      echo '   root-keys: 07c59cb65787dedfaef5bd5f987ceb5f7e5ebf88b904bbd4c5cbdeb2ff71b740' >> cabal.project
+      echo '              2e8555dde16ebd8df076f1a8ef13b8f14c66bad8eafefd7d9e37d0ed711821fb' >> cabal.project
+      echo '              8f79fd2389ab2967354407ec852cbe73f2e8635793ac446d09461ffb99527f6e' >> cabal.project
+      echo '   key-threshold: 3' >> cabal.project
+    fi
+  - cat cabal.project
+  # this builds all libraries and executables (without tests/benchmarks)
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks all
+
+  # Build with installed constraints for packages in global-db
+  - if $INSTALLED; then echo cabal new-build -w ${HC} --disable-tests --disable-benchmarks $(${HCPKG} list --global --simple-output --names-only | sed 's/\([a-zA-Z0-9-]\{1,\}\) */--constraint="\1 installed" /g') all | sh; else echo "Not building with installed constraints"; fi
+
+  # build & run tests, build benchmarks
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} all
+  - if [ "x$TEST" = "x--enable-tests" ]; then cabal new-test -w ${HC} ${TEST} all; fi
+
+  # haddock
+  - rm -rf ./dist-newstyle
+  - if $HADDOCK; then cabal new-haddock -w ${HC} --disable-tests --disable-benchmarks all; else echo "Skipping haddock generation";fi
+
+# REGENDATA ["-o",".travis.yml","--irc-channel=irc.freenode.org#clash-lang","ghc-typelits-natnormalise.cabal"]
+# EOF
